name: Dependabot auto-approve
on: pull_request_target

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-22.04
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2.2.0
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            - name: Enable auto-merge for Dependabot PRs
              if: ${{contains(steps.metadata.outputs.dependency-names, 'kubectl')}}
              run: gh pr merge --auto --merge "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - uses: actions/checkout@v4
              if: ${{contains(steps.metadata.outputs.dependency-names, 'kubectl')}}
              with:
                  fetch-depth: 0
                  ref: "${{github.event.pull_request.head.sha}}"

            - name: Parse version
              if: ${{contains(steps.metadata.outputs.dependency-names, 'kubectl')}}
              run: |
                  cat Dockerfile|grep "FROM bitnami/kubectl"| sed -e 's/.*kubectl\:\([0-9.]\+\).*/\1/' > version.txt
                  echo "KUBECTL_VERSION=$(cat version.txt | tr -d '\n')" >> $GITHUB_ENV
                  echo ">> Version: $(cat version.txt | tr -d '\n')"

            - name: Create new release for a new kubectl release
              if: ${{contains(steps.metadata.outputs.dependency-names, 'kubectl')}}
              run: gh release create v${{ env.KUBECTL_VERSION }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_RW_TOKEN }}
